version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Port de RabbitMQ pour l'application
      - "15672:15672"    # Port de l'interface de gestion Web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    build:
      context: .                # Répertoire contenant le Dockerfile
      dockerfile: Dockerfile    # Nom du Dockerfile
    container_name: nestjs-app
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672  # URL de RabbitMQ via Docker Compose
    ports:
      - "3000:3000"  # Port de l'application NestJS