version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ connection port
      - "15672:15672"    # RabbitMQ management dashboard port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    build:
      context: .                # Points to the Dockerfile location
      dockerfile: Dockerfile    # Dockerfile name
    container_name: nestjs-app
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672  # URL for connecting to RabbitMQ
    ports:
      - "3000:3000"  # Expose NestJS app on port 3000
